<a href="https://colab.research.google.com/github/jae-hyuck/dl13/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ch02_numpy.ipynb
 - numpy 공부

In [11]:
# chap02 - numpy
import numpy as np


In [12]:
# ndarray
a = np.array([1, 2, 3])

print(a[0])
a, type(a) #ndarray - n차원배열

1


(array([1, 2, 3]), numpy.ndarray)

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b)

b[0][2] #index 0번행2번열


[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [14]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

a.shape, a.ndim, a.dtype, a.itemsize, a.size


((3, 3), 2, dtype('int64'), 8, 9)

In [15]:
np.zeros( (3, 4) )	

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones( (3, 4) )#, dtype=np.int32 )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x = np.ones(5, dtype=np.int64)

x

array([1, 1, 1, 1, 1])

In [22]:
print(np.arange(5))

print(np.arange(1, 6))

np.arange(1, 10, 2)


[0 1 2 3 4]
[1 2 3 4 5]


array([1, 3, 5, 7, 9])

In [24]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [25]:
# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])

x,y

array([[5, 6],
       [7, 8]])

In [33]:
np.concatenate((x, y), axis=0)
#  np.concatenate((x, y), axis=1)


np.vstack((x, y))

np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [34]:
# reshape
a = np.arange(12)

a.shape

(12,)

In [38]:
# a.reshape(3, 4)

# a.reshape(6, -1)
a.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [40]:
array = np.arange(30).reshape(-1, 10)

array, array.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), (3, 10))

In [41]:
arr1, arr2 = np.split(array, [3], axis=1)

arr1, arr2

(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]]), array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19],
        [23, 24, 25, 26, 27, 28, 29]]))

In [42]:
# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [43]:
a1 = a[np.newaxis, :]

a1, a1.shape

(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [44]:
a2 = a[:, np.newaxis]

a2.shape

(6, 1)

### numpy - ndexing & slicing

In [45]:
# indexing & slicing
ages = np.array([18, 19, 25, 30, 28])

ages[1:3] , ages[:2] 

(array([19, 25]), array([18, 19]))

In [46]:
y = ages > 20

print(y) # 조건을 만족하는 데이터 선택

ages[ ages > 20 ]

[False False  True  True  True]


array([25, 30, 28])

In [47]:
# 인덱싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 2])

a[0, 0] = 12

a

3


array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [48]:
# 슬라이싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

### numpy 연산
 - elementwise operation
 - vectorwise operation

In [49]:
# operation of arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[1, 1], [1, 1], [1, 1]])

result = arr1 + arr2

result

array([[2, 3],
       [4, 5],
       [6, 7]])

### 브로드캐스팅 (broadcasting)

In [50]:
miles = np.array([1, 2, 3])

result = miles * 1.6

result

array([1.6, 3.2, 4.8])

In [52]:
 # elementwise multiplication
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 * arr2

result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [51]:
# vectorwise multiplication
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 @ arr2

result

array([[12, 12],
       [30, 30],
       [48, 48]])

In [55]:
arr1,arr2

(array([[1, 2],
        [3, 4],
        [5, 6]]), array([[2, 2],
        [2, 2],
        [2, 2]]))

In [ ]:
A = np.array([0, 1, 2, 3])

10 * np.sin(A)

In [56]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a.sum(), a.min(), a.max()


(45, 1, 9)

In [57]:
a.argmin(), a.argmax() # 전체값중 min값과 max값의 인덱스

(0, 8)

In [59]:
scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])   # - 학생 4명의 3과목의 시험점수
 
scores.mean() # 전체평균

scores.mean(axis=1) # 각학생의 평균 점수
scores.mean(axis=0) # 과목별 평균점수


array([84.        , 91.        , 79.66666667, 80.33333333])

### 무작위수 배열

In [66]:
# random numbers
np.random.seed(100)

# np.random.rand(5), np.random.rand(5)

# np.random.rand(5, 3)

# np.random.randn(5) #정규분포 만들기

np.random.randn(5, 4) # 배열 만들기


array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

### [DIY]
 - 컬러 이미지 100장을 무작위로 생성
 - 이미지 크기는 28 X 28

In [67]:
image100 = np.random.randn(100, 28, 28, 3)
image100.shape

(100, 28, 28, 3)

In [69]:
m, sigma = 10, 2 # 평균값 10 표준편차 2 인 가우시안분포

m + sigma*np.random.randn(5)

array([10.09750826, 10.64421076,  8.47769239, 10.09356629,  9.31069176])

In [68]:
mu, sigma = 10, 2 	# 평균과 표준 편차

np.random.normal(mu, sigma, 5)

array([ 8.12600727, 10.07239857,  8.639449  ,  8.44707082,  9.82908791])

## np.unique()

In [71]:

# unique()
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
# a.size

unique_values = np.unique(a)

unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
uv.unique(a,return_index = Ture)

AttributeError: ignored

In [72]:
uv, uc = np.unique(a, return_counts=True)
uv,uc

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [ ]:

# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


x.flatten()



## pandas, matplotlib

In [ ]:
########################
# Pandas
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

########################
# matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()


import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()


X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()


import matplotlib.pyplot as plt 
import numpy as np 
  
X = np.linspace(-10, 10, 101) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 


import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 101) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 





